"""
Problem 2 Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
import math
import numpy as np


def

test = 10
exercise = 4000000
first = 1
second = 1
third = 0
sum= 0
while third<exercise:
    third = first + second
    first = second
    second = third
    if third % 2 == 0:
        sum=third+sum
print(sum)